### ISSUE TITLE
Replace copy

### ISSUE THREAD

**Issue by jcahail** [ImpactView/impact-view-philly#10]
And add logo.
![impactview_logo_web.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/589230cab101581a00895a21/125516c66e82c728ace21e0d46e1998a228197bf86eca87ca852f79b165122716b48e13b628ae92dbc56395b4d5a46a5435b5e46f8fcd82cf2e06d72885c0bb8d63f5f25c02f0dbefad341eb5ee779c11ac7a4b6984dc8e23c20e7838a4e3f1a0d1b8cf75927ed.png)

**Comment by CloudNiner** [comment]
@nevillevak might want to start thinking about the copy you'd like to have for the site, and send it to us separately as a google doc or some other text format. We'll need text for the footer boxes on the homepage, as well as for each of the "About", "Getting Started" and "Contact Us" pages. If any of those pages don't make sense, we can just remove them as well.

**Comment by nevillevak** [comment]
Will do! Thanks.

Best,
Neville
_____________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University
Westphal College of Media Arts & Design
215.571.4439
nvakharia@drexel.edu

________________________________

**Comment by CloudNiner** [comment]
Initial copy text is attached in #32
