### ISSUE TITLE
Update data fields in app

### ISSUE THREAD

**Issue by CloudNiner** [ImpactView/impact-view-philly#12]
@nevillevak Which fields in the source google sheet/carto table should appear in the following places?

Search list view:
![screen shot 2017-10-23 at 14 34 14](https://user-images.githubusercontent.com/1818302/31906557-6065b836-b7ff-11e7-8f39-0b28e37bd220.png)

Map popup:
![screen shot 2017-10-23 at 14 34 21](https://user-images.githubusercontent.com/1818302/31906569-6bc2561c-b7ff-11e7-8d05-e11e1732f569.png)

Detail view:
![screen shot 2017-10-23 at 14 34 27](https://user-images.githubusercontent.com/1818302/31906623-8fa81aa8-b7ff-11e7-8ae0-83fb9121869e.png)

**Comment by nevillevak** [comment]
@CloudNiner - here you go!

**For Search list view:**
Organization Name (Organization_NEW)
Type (NTEE_Org_Type_NEW)
Budget Size (Org_Size_Label_NEW)
URL (Org_Website_NEW)

Ideally, the URL is hyperlinked.

**For Map Pop-up/Hover:**
Organization Name (Organization_NEW)
Type (NTEE_Org_Type_NEW)
Budget Size (Org_Size_Label_NEW)

**For Detail View:**
Organization Name (Organization_NEW)
Address 1 (Org_Address1_NEW), Address 2 (Org_Address2_NEW)
City (Org_City_NEW), State (Org_State_NEW), Zip (Org_Zip_NEW)
Phone Number (Org_Phone_NEW), URL (Org_Website_NEW)
Type (NTEE_Org_Type_NEW)
Budget Size (Org_Size_Label_NEW)
Year Founded (Year_Founded_990)
Mission/Purpose (Org_Mission_NEW)

**Comment by CloudNiner** [comment]
👍 

For the "Year Founded" field in the detail view, that appears to be the only one sourced from the 990 file. Would the other source datasets just not display this value? Or is it present in the other sources, but with a different name?

**Comment by nevillevak** [comment]
Correct. Only the 990 has that field. For others, we just wouldn't display it.

_____________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University
Westphal College of Media Arts & Design
215.571.4439
nvakharia@drexel.edu

________________________________

**Comment by CloudNiner** [comment]
Closed by #16 and by setting proper values for map popup in the carto viz.
