### ISSUE TITLE
Determine treatment for mission statement

### ISSUE THREAD

**Issue by jcahail** [ImpactView/impact-view-philly#13]
Mission statements range in size from two words to two paragraphs, and we'll need a consistent way to display them (on the details page, at least). 

Per @CloudNiner one suggestion might be to show the first x number of characters, followed by an ellipsis and a "more" link, which would then display the remaining text.

**Comment by CloudNiner** [comment]
@designmatty do you have any issues with the "more" link strategy, where the remainder of the mission statement is hidden behind a "more" link, and only expanded if the character count of the mission statement is only greater than some threshold (maybe 256 chars)? Any preferable solutions?

Here's the longest mission statement in the table @ 1379 chars:

![screen shot 2017-11-03 at 11 24 35](https://user-images.githubusercontent.com/1818302/32381747-dc76ff24-c089-11e7-8703-a00073cf40a3.png)

Some extra statistics:
- ~320 with > 350 chars, which is about three lines of text in the UI
- ~550 with > 256 chars, probably a first sensible attempt at a cutoff
- 2329 total in db

**Comment by CloudNiner** [comment]
Offline discussion with Matt: "...the more link would be fine".

**Comment by CloudNiner** [comment]
Closed by #22
