### ISSUE TITLE
Update search options in dropdown on home view

### ISSUE THREAD

**Issue by CloudNiner** [ImpactView/impact-view-philly#14]
Some of the search options, such as "city" no longer apply. The search by geolocation button also probably no longer makes sense.

Review the search options with @nevillevak and @jcahail and choose a new set, then update the search feature to match.

Ensure that the search bbox is limited to Philadelphia, so that non-phila addresses/locations don't show up.

**Comment by nevillevak** [comment]
@CloudNiner @jcahail 

How about having making it "Search By Organization, Address, or Zip Code"?

When selecting Zip Code, the search results would be every entity within the zip code (just as MuseumStat does).

Let me know what you think.

**Comment by CloudNiner** [comment]
This should work.
