### ISSUE TITLE
Re-implement demographics layers on both home and detail maps

### ISSUE THREAD

**Issue by CloudNiner** [ImpactView/impact-view-philly#27]
Layers desired by @nevillevak:
- [x] Median Household Income (median_income_households)
- [x] Poverty Rate (poverty_percent_below)
- [x] Percent Children (population_children_under_18_percent)
- [ ] Percent Adults without HS Diploma (educational_attainment_percent_hs_grad_or_higher) (Note: 100 – above = without HS Diploma)

**Comment by CloudNiner** [comment]
@nevillevak @jcahail @designmatty have a bit of a problem adding the demographics control back onto the map. We're quickly running out of space to display things:

![screen shot 2017-11-17 at 14 03 21](https://user-images.githubusercontent.com/1818302/32964130-2e8d119c-cba0-11e7-8c96-188bd14e947f.png)

This is the best I could do with the available space in the worst case scenario -- all controls exist and are expanded. The screenshot doesn't show the carto "loading" spinner that appears when the map layers are loading, which appears as a square just below the zoom control. In the configuration above its partially or completely obscured by the demographics control.

How would you like to address this and/or reshuffle the map controls?

**Comment by designmatty** [comment]
We could implement map controls (think a map layer picker), which when clicked, would open the panels which are currently all stacked on the right. The user doesn't need to see all those options on screen all at once. They should be hidden away until they actually wish to use them.

**Comment by jcahail** [comment]
I like that idea.

**Comment by CloudNiner** [comment]
I could do that. Leave it in the bottom right and expand up and left? We'd likely still have to increase the map size if we did that, I'm not sure there's enough vertical height ATM to show all those controls at once. Maybe I'm misunderstanding though?

**Comment by designmatty** [comment]
More like this:
![large gif 348x274](https://user-images.githubusercontent.com/1928955/32964806-645e1de6-cba2-11e7-81aa-d59657d78e87.gif)

so a tool which pops open for analysis, organization filter, demographic filters, whatever other panel types.

So in essence, you'd have like 3 or 4 buttons which you could open up their dialog like the gif above

**Comment by CloudNiner** [comment]
Got it. 👍
