### ISSUE TITLE
Remove "draw custom area" and "custom radius" icons

### ISSUE THREAD

**Issue by jcahail** [ImpactView/impact-view-philly#28]
That functionality will not be implemented.

**Comment by nevillevak** [comment]
@jcahail @CloudNiner - I think we should use 0.5 miles as the default radius when on the results screen and for the visualizations below the map, with 0.25, 0.5, 1, 2.5, and 5 as the drop-down options. What do you think?

**Comment by CloudNiner** [comment]
I'm fine with that set of options in the dropdown. I'll fix that up today. 

@jcahail you had mentioned in passing that the custom draw options were broken. I was able to reproduce an error, but only once at staging.impactview.org, and not locally on an up-to-date version of the code. I'll test a bit more and let you know whether its better to remove or fix.

**Comment by jcahail** [comment]
Agreed- .5 miles seems good.

Jessica Cahail, Project Manager

Azavea |  990 Spring Garden Street, 5th Floor, Philadelphia, PA
jcahail@azavea.com <jbranigan@azavea.com>  | T 215.701.7722  | F
215.925.2663
Web azavea.com <http://www.azavea.com/>  |  Blog azavea.com/blogs
<http://www.azavea.com/Blogs>  | Twitter @azavea <http://twitter.com/azavea>
