### ISSUE TITLE
Add Content for "About "Getting Started" and "Contact"

### ISSUE THREAD

**Issue by nevillevak** [ImpactView/impact-view-philly#32]
Attached is the text content for the three pages. Note that once it's all up and we have everything in place, I'll likely have some minor edits to it. 
----
Note:
- for the impactview logo, please add the "beta" tag as we've done with MuseumStat
- I don't think we need the three footer text blocks as we did with MuseumStat, but we do need the Drexel Westphal Logo and the Stanford PACS logo (I can re-send if needed).
- As discussed, we'll go with a light-colored design, not the gray/dark used in MuseumStat. 
----
[ImpactView Philadelphia - Web Content and Other Details.docx](https://github.com/ImpactView/impact-view-philly/files/1485720/ImpactView.Philadelphia.-.Web.Content.and.Other.Details.docx)

**Comment by CloudNiner** [comment]
I'll let @jcahail confirm, but I don't think we have the Stanford logo.

**Comment by CloudNiner** [comment]
@designmatty I updated the text based on the above doc for each of the static pages and removed the footer text blocks. I'll leave the rest of this task's bullet points to you as part of the final styling cleanup.

**Comment by jcahail** [comment]
@nevillevak I don't seem to have the Stanford PACS logo in my inbox. Is this the one you want to use? 
https://goo.gl/images/htvvGn

**Comment by nevillevak** [comment]
Yes, please. Thanks!

Best,
Neville
_________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, Suite 210
nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>
215.571.4439

**Comment by designmatty** [comment]
I'll take care of the rest this sprint.
