### ISSUE TITLE
Remove "Submit Organization Update" link?

### ISSUE THREAD

**Issue by CloudNiner** [ImpactView/impact-view-philly#35]
Currently lives on the detail view:

![screen shot 2017-11-20 at 14 24 09](https://user-images.githubusercontent.com/1818302/33037125-8b73c292-cdfe-11e7-8967-eec8351e73b5.png)

Is this link still useful @nevillevak or should it be removed?

**Comment by jcahail** [comment]
@nevillevak Do you plan to field updates from organizations at all? If not, it would be best to remove this.
