### ISSUE TITLE
Responses to @jcahail's questions and general items

### ISSUE THREAD

**Issue by nevillevak** [ImpactView/impact-view-philly#51]
Hi All - I've responded to @jcahail's questions in the document linked below. I also had a couple general items, which you may already be addressing. Let me know when you are ready for me to take another look at anything. Thanks!

https://docs.google.com/document/d/1Hj7joRumllG3EYmG8mnG11huCQu9Xpq_vhCcmMsAHMY/edit?usp=sharing

**Comment by CloudNiner** [comment]
Only item in this document not addressed by other issues is to bump the default map zoom by one.
