### ISSUE TITLE
Search Bar Text

### ISSUE THREAD

**Issue by nevillevak** [ImpactView/impact-view-philly#57]
Hi - Just noticed this minor item. When you search for a street address and select it, the map zooms to the location, but does not drop a pin on the address. The search results list all orgs in the zip code. We should either drop a pin so the user can see the address, or only allow users to search by org and zip code. I'd prefer to drop a pin, but let me know what your suggestions are.

**Comment by CloudNiner** [comment]
I should be able to update the app to drop a pin at the location of the geocoded result. I think that's the fastest, simplest, clearest solution.

**Comment by nevillevak** [comment]
Perfect.

Best,
Neville
_________________
Neville K. Vakharia
Assistant Professor and Research Director
Program Director, Arts Administration
Drexel University, Westphal College of Media Arts & Design
Department of Arts & Entertainment Enterprise
URBN Center, Suite 210
nvakharia@drexel.edu<mailto:nvakharia@drexel.edu>
215.571.4439
